class ViewExc(Exception):
	"""docstring for ViewExc"""
	
	exceptions = {"OverflowError": "Number generated by this representation is to large. Try a smaller sequence or another method"}

	def __init__(self, exc_name):
		super(ViewExc, self).__init__(self.exceptions.get(exc_name))
		
		